"""`fitme.i18n` (A§5, A§6, A§9.1, IMPLEMENTATION_PLAN M3)."""

from __future__ import annotations

import pytest

from fitme import i18n


def test_supported_languages_includes_en_and_ru() -> None:
    langs = i18n.supported_languages()
    assert "en" in langs
    assert "ru" in langs


def test_supported_languages_lists_en_first() -> None:
    assert i18n.supported_languages()[0] == "en"


@pytest.mark.parametrize(
    ("code", "expected"),
    [
        ("ru-RU", "ru"),
        ("ru_RU", "ru"),
        ("en-US", "en"),
        ("en", "en"),
        ("RU", "ru"),
        (None, "en"),
        ("", "en"),
        ("fr-FR", "en"),  # unsupported language falls back to en
        ("xx", "en"),
    ],
)
def test_resolve_language(code: str | None, expected: str) -> None:
    assert i18n.resolve_language(code) == expected


def test_t_returns_the_localized_string() -> None:
    assert i18n.t("disclosure.ai", "en") == "Plans are generated by AI. This is not medical advice."
    assert i18n.t("disclosure.ai", "ru").startswith("Планы создаются ИИ")


def test_t_fills_in_format_params() -> None:
    text = i18n.t("checkin.question", "en", area="lower back")
    assert text == "How did your lower back feel?"


def test_t_falls_back_to_en_for_an_unsupported_language() -> None:
    assert i18n.t("disclosure.ai", "fr") == i18n.t("disclosure.ai", "en")


def test_t_lenient_by_default_logs_and_returns_the_bare_key(
    caplog: pytest.LogCaptureFixture,
) -> None:
    with caplog.at_level("WARNING"):
        result = i18n.t("nonexistent.key", "en")
    assert result == "nonexistent.key"
    assert "nonexistent.key" in caplog.text


def test_t_strict_raises_on_a_missing_key() -> None:
    with pytest.raises(i18n.MissingTranslationKeyError):
        i18n.t("nonexistent.key", "en", strict=True)


def test_keys_returns_every_flattened_key_for_a_language() -> None:
    keys = i18n.keys("en")
    assert "disclosure.ai" in keys
    assert "enum.location.public_gym" in keys


def test_format_params_extracts_named_placeholders() -> None:
    assert i18n.format_params("checkin.question", "en") == frozenset({"area"})
    assert i18n.format_params("disclosure.ai", "en") == frozenset()


def test_format_params_raises_on_a_missing_key() -> None:
    with pytest.raises(i18n.MissingTranslationKeyError):
        i18n.format_params("nonexistent.key", "en")


def test_check_parity_is_clean_for_the_real_locales() -> None:
    assert i18n.check_parity() == []


def test_check_parity_detects_a_missing_key() -> None:
    problems = i18n.check_parity(("en",))
    # a single language trivially has parity with itself; nothing to compare
    assert problems == []


def test_check_parity_detects_missing_keys_and_param_mismatches(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    tables = {
        "en": {"a.b": "Hello {name}", "only_en": "x"},
        "xx": {"a.b": "Bonjour {who}"},
    }
    monkeypatch.setattr(i18n, "_load_lang", lambda lang: tables[lang])

    problems = i18n.check_parity(("en", "xx"))

    assert any("only_en" in p and "xx" in p for p in problems)
    assert any("a.b" in p and "mismatched format params" in p for p in problems)
