"""`bot/plan_rendering.py` (A§6.4 step 5): explicit load on every prescription, the
per-dumbbell label, calibration wording with the catalog start, localized weekdays, grouped
supersets, and the Telegram 4096-character split."""

from __future__ import annotations

from fitme.bot.plan_rendering import (
    TELEGRAM_MESSAGE_LIMIT,
    load_label,
    render_plan_text,
    split_message,
)
from fitme.catalog import load_catalog
from fitme.domain.models import Block, Load, Plan, Prescription, ScheduledDay, Workout


def _prescription(exercise_id: str, load: Load) -> Prescription:
    return Prescription(
        exercise_id=exercise_id, sets=3, reps_min=8, reps_max=10, load=load, rest_seconds=90
    )


_PLAN = Plan(
    name="Test plan",
    schedule=[ScheduledDay(weekday=0, workout_key="A"), ScheduledDay(weekday=3, workout_key="B")],
    workouts=[
        Workout(
            key="A",
            title="Lower",
            blocks=[
                Block(
                    kind="single",
                    items=[_prescription("barbell_back_squat", Load(kind="kg", kg=42.5))],
                ),
                Block(
                    kind="superset",
                    items=[
                        _prescription("dumbbell_bench_press", Load(kind="kg", kg=12.5)),
                        _prescription("pushup", Load(kind="bodyweight")),
                    ],
                ),
            ],
        ),
        Workout(
            key="B",
            title="Calibration day",
            blocks=[
                Block(
                    kind="single",
                    items=[_prescription("barbell_back_squat", Load(kind="calibration"))],
                )
            ],
        ),
    ],
)


def test_every_prescription_line_shows_an_explicit_load_in_english() -> None:
    text = render_plan_text(_PLAN, catalog=load_catalog(), lang="en", title="Draft:")
    lines = [line for line in text.splitlines() if "×" in line]
    assert len(lines) == 4
    assert all(" @ " in line for line in lines)
    assert "Barbell back squat: 3 × 8–10 @ 42.5 kg, rest 90 s" in text
    assert "Dumbbell bench press: 3 × 8–10 @ 12.5 kg each" in text
    assert "Push-up: 3 × 8–10 @ bodyweight" in text
    assert "@ calibration: start with 20 kg or lighter, log what you used" in text
    assert "Monday: A — Lower" in text and "Thursday: B — Calibration day" in text
    assert "Superset:" in text
    assert text.rstrip().endswith("Plans are generated by AI. This is not medical advice.")


def test_rendering_uses_the_users_language_for_names_weekdays_and_loads() -> None:
    text = render_plan_text(_PLAN, catalog=load_catalog(), lang="ru", title="Черновик:")
    assert "Приседания со штангой на спине: 3 × 8–10 @ 42.5 кг" in text
    assert "12.5 кг каждая" in text
    assert "Понедельник: A — Lower" in text
    assert "калибровка: начните с 20 кг" in text
    assert "собственный вес" in text


def test_load_label_for_unknown_exercise_and_calibration_without_a_kg_start() -> None:
    catalog = load_catalog()
    pushup = catalog.by_id("pushup")
    assert pushup is not None
    # A bodyweight start gets the plain wording: "or lighter" only makes sense for a kg start.
    assert load_label(Load(kind="calibration"), pushup, "en") == (
        "calibration: start light, log what you used"
    )
    assert load_label(Load(kind="calibration"), None, "en") == (
        "calibration: start light, log what you used"
    )
    assert load_label(Load(kind="kg", kg=40), None, "en") == "40 kg"


def test_load_label_follows_the_catalog_load_unit() -> None:
    catalog = load_catalog()
    per_dumbbell = catalog.by_id("dumbbell_bench_press")
    single = catalog.by_id("dumbbell_goblet_squat")
    total = catalog.by_id("barbell_back_squat")
    assert per_dumbbell is not None and single is not None and total is not None
    assert per_dumbbell.load_unit == "per_implement"
    assert single.load_unit == "single_implement"
    assert load_label(Load(kind="kg", kg=12.5), per_dumbbell, "en") == "12.5 kg each"
    assert load_label(Load(kind="kg", kg=16), single, "en") == "16 kg"  # one implement: plain kg
    assert load_label(Load(kind="kg", kg=60), total, "en") == "60 kg"
    assert single.start.kind == "kg" and single.start.kg is not None
    assert load_label(Load(kind="calibration"), single, "en") == (
        f"calibration: start with {single.start.kg:g} kg or lighter, log what you used"
    )


def test_split_message_respects_the_telegram_limit_on_line_boundaries() -> None:
    text = "\n".join(f"line {i:04d} " + "x" * 90 for i in range(200))
    assert len(text) > TELEGRAM_MESSAGE_LIMIT
    chunks = split_message(text)
    assert len(chunks) > 1
    assert all(len(chunk) <= TELEGRAM_MESSAGE_LIMIT for chunk in chunks)
    assert "\n".join(chunks) == text
    assert all(chunk.startswith("line ") for chunk in chunks)  # split between lines


def test_split_message_cuts_an_over_long_single_line() -> None:
    text = "y" * (TELEGRAM_MESSAGE_LIMIT * 2 + 10)
    chunks = split_message(text)
    assert [len(c) for c in chunks] == [TELEGRAM_MESSAGE_LIMIT, TELEGRAM_MESSAGE_LIMIT, 10]
    assert "".join(chunks) == text
    assert split_message("short") == ["short"]
